### ISSUE TITLE
Initial organization of the landing page

### ISSUE THREAD

**Issue by nearmax** [near/community#1]
I suggest we organize this page just like https://github.com/rust-embedded/ and add the content to the landing page.

**Comment by potatodepaulo** [comment]
@nearmax I'm confused. You want to organize the content of the main landing page (nearprotocol.com) like rust-embedded's github?

**Comment by nearmax** [comment]
I did not paste the full URL in the original post. I suggest we organize this repo similarly to https://github.com/rust-embedded/wg . Someone would have to put an effort into creating a similar landing page. I don't know whether you are the right person to assign to this issue, but you are the first who came to mind. Please reassign if needed.

**Comment by nearmax** [comment]
@AnaisUrlichs fixed it in https://github.com/near/community/pull/3 Closing
