### ISSUE TITLE
[Discussion] Reorganization of Middleware and Explorer Syncs

### ISSUE THREAD

**Issue by nearmax** [near/community#13]
I suggest we split the Middleware sync that currently lasts 1 hour and involves 7+ people into 30-minute syncs following one after another, extract RPC out, and bulk L2 projects together. The proposed schedule would be the following:
* 8:30AM-8:55AM PDT RPC + network indexer led by whoever is leading explorer sync right now;
* 9:00AM-9:25AM PDT Transaction runtime led by @frol or @evgenykuzyakov depending on what is currently being worked on;
* 9:30AM-9:55AM PDT Contract runtime led by @olonho ;
* 10:00AM - 10:25AM PDT Contracts and bridge led by @evgenykuzyakov and @k06a ;

The advantages:
* Currently we have 7+ people in middleware sync, which makes it slow and boring. The rule of thumb for people speaking at the meeting is less than 5-6 people. By splitting it into smaller meetings people do not need to sit and wait for 1 hour for their turn to talk about their work. At the same time if they are interested to listen they can stay through any or all meetings;
* Projects that are adjacent in time have certain relationships. Examples:
  * Someone working on modifying the actions can join the RPC call and then stay through the transaction runtime;
  * Someone working on the standalone runtime can join the transaction runtime and then stay through the contract runtime;
  * Someone working on AssemblyScript can join the contract runtime and then stay through the contracts development call.
* Projects do not have strict assignment of people working on them. While there is always more or less at least one person leading each of the above projects, there is fluidity in who else is working on it and how their time is split with other projects. With the proposed scheme they can leave or join other meetings based on what they are currently working on;
* Less context switch for engineering. Instead of disrupting three engineering days, we disrupt only one. Plus we run the syncs next to each other in time so that they take only half a day.

I propose we run this sync on Friday. The rationale is the following -- we want the sync to happen shortly before our engineering sync on Monday, so that on Monday we can discuss the summary of the projects and the information is going to be up to date. We cannot schedule it on Monday and stagger engineering sync because the timezones only allow us about 3 hour window per day. If we schedule it in the middle of the week it is going to be disruptive for the engineering -- the more consecutive no meeting days we have for engineering the better.

**Comment by evgenykuzyakov** [comment]
I like the idea to move sync to Friday. Let's try this format to see if it works.

**Comment by frol** [comment]
Sounds good to me. Let's give it a try.

**Comment by olonho** [comment]
Fine with me as well.

вт, 26 мая 2020 г. в 21:57, Vlad Frolov <notifications@github.com>:

**Comment by willemneal** [comment]
Same here
