### ISSUE TITLE
[Question from Portal] Hey! Anais, I recently joined this program so I have some questions for you 

1. Do I need to submit my work one by one after it completed or need to submit at once a month? 

2. I want to create  telegram, twitter and a medium channel for Indian community so I want to know is there any exiting channel for indian community? 

3. Do I need to as you as an admin after I create all channels? 

4. What if I translate articles into Hindi and Odia? 

5. Where I can meet with other guild of my region?

### ISSUE THREAD

**Issue by ashleynear** [near/community#21]
**Content of the question:**
Hey! Anais, I recently joined this program so I have some questions for you 

1. Do I need to submit my work one by one after it completed or need to submit at once a month? 

2. I want to create  telegram, twitter and a medium channel for Indian community so I want to know is there any exiting channel for indian community? 

3. Do I need to as you as an admin after I create all channels? 

4. What if I translate articles into Hindi and Odia? 

5. Where I can meet with other guild of my region?

**Link to question:**
Https://portal.near.org/question/5f0e0899644bef3dc0f3d95e

**Question from**
Jitendra Naik

**Comment by AnaisUrlichs** [comment]
Replied on the Portal
