### ISSUE TITLE
PGP signatures for email, github and everything else

### ISSUE THREAD

**Issue by nearmax** [near/community#4]
We should enable PGP signatures for all our communication within Near collective.

**Comment by vgrichina** [comment]
That really doesn't seem practical at all. How do you do it for Gmail? Or Slack? Or Github?

**Comment by nearmax** [comment]
Plenty of email clients support PGP. For git see: https://help.github.com/en/github/authenticating-to-github/managing-commit-signature-verification

**Comment by ilblackdragon** [comment]
Seems like a wrong place to discuss this? 🤷  Going to close this.
For signing on github - just start requiring that when you are doing PR reviews.

**Comment by nearmax** [comment]
As discussed in Slack we need to have a record of every security concern that we have in mind, since we are running the security vulnerability bounty program. If someone finds security issue that we are aware of we should be able to present a proof (a github issue) explaining that we are aware of it.

AFAIU we don't have a place for OpSec and InfoSec issues, so as a fallback I suggest we keep these issues in here.

> For signing on github - just start requiring that when you are doing PR reviews.

We need to make sure everyone on the team is signing with PGP and this restriction is enabled in the repo settings. Since this is not done yet, I am reopening this issue.

Also, we haven't done a thorough investigation of what other security critical things should be signed with pgp. Until we have this investigation I suggest we keep this issue open.

**Comment by ilblackdragon** [comment]
The issues in this repo are used for bounties and community suggestions / bounties and feedback.
This is also community repo, not "team"'s by any definition of it. We can create a separate repo if we want to track issues as this.
